# Generated by Django 3.2.10 on 2021-12-20 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20211214_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Libro'},
        ),
    ]
