# Generated by Django 3.2.10 on 2021-12-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stocked',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
