# Generated by Django 3.2.10 on 2021-12-29 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_rename_stocked_book_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
    ]
