# Generated by Django 3.2.10 on 2021-12-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
