# Generated by Django 3.2.10 on 2021-12-16 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20211214_2206'),
        ('reader', '0002_alter_bookloan_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_book', to='book.book'),
        ),
    ]
