# Generated by Django 3.2.10 on 2021-12-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0003_alter_bookloan_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reader',
            options={'verbose_name': 'Reader', 'verbose_name_plural': 'Readers'},
        ),
    ]
