# Generated by Django 3.2.10 on 2021-12-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='nickname',
            new_name='appellative',
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('country', 'appellative')},
        ),
    ]
